name: Addon Updates (Dev)

on:
  workflow_dispatch:
  push:
    branches: [main, dev, beta, stable]

jobs:
  generate:
    name: Generate Addon Update Manifests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Gluon
        run: yarn

      - name: Load config
        run: yarn gluon ci --brand dev

      - name: Generate update manifest
        run: yarn gluon updates-addons

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: JaduaStudios/GoUpdates
          path: updates
          token: ${{ secrets.ROBOT_TOKEN }}

      - name: Copy update manifests
        run: |
          mkdir -p updates/browser
          cp -a dist/update/. updates/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🔖 Upload update addon manifests
          commit_user_name: Jadua Studios Bot
          commit_user_email: info@jaduastudios.com
          repository: ./updates
